"""users table

Revision ID: 27acc5800698
Revises: 
Create Date: 2020-02-13 18:37:01.561206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27acc5800698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('units', sa.String(length=1), nullable=True),
    sa.Column('mail_hour', sa.String(length=2), nullable=True),
    sa.Column('mail_minute', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_mail_hour'), 'user', ['mail_hour'], unique=False)
    op.create_index(op.f('ix_user_mail_minute'), 'user', ['mail_minute'], unique=False)
    op.create_index(op.f('ix_user_units'), 'user', ['units'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_units'), table_name='user')
    op.drop_index(op.f('ix_user_mail_minute'), table_name='user')
    op.drop_index(op.f('ix_user_mail_hour'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
